"""
backend/main.py

NeuroLens FastAPI application entry point.

Run with:
    cd backend
    uvicorn main:app --reload --port 8000

API docs (auto-generated by FastAPI):
    http://localhost:8000/docs       ← Swagger UI
    http://localhost:8000/redoc      ← ReDoc
"""

from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from loguru import logger

from app.core.database import create_tables
from app.core.config import get_settings
from app.routers import auth, documents, chat, websocket, system

settings = get_settings()


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup and shutdown logic."""
    logger.info("🚀 NeuroLens API starting up...")

    # Create all DB tables (idempotent — safe to run every startup)
    await create_tables()
    logger.info("✅ Database tables ready")

    # Pre-warm the NPU embedding model in the background
    # (first inference takes ~2s for JIT compilation on NPU — warm up here
    # so the first user request isn't slow)
    import asyncio
    async def warmup():
        try:
            from npu_engine.inference.embedding_runner import EmbeddingRunner
            runner = EmbeddingRunner.get_instance()
            runner.embed(["warmup"])
            logger.info(f"✅ Embedding model warmed up on [{runner.provider}]")
        except Exception as e:
            logger.warning(f"NPU warmup skipped: {e} (will load on first request)")

    asyncio.create_task(warmup())

    yield  # App runs here

    logger.info("👋 NeuroLens API shutting down")


app = FastAPI(
    title="NeuroLens API",
    description=(
        "AI-Powered Document Intelligence Platform with NPU Acceleration.\n\n"
        "Combines on-device NPU inference (AMD Ryzen AI), RAG with Llama 3, "
        "voice I/O, and financial entity extraction."
    ),
    version="0.1.0",
    lifespan=lifespan,
)

# ── CORS ──────────────────────────────────────────────────────────────────────
# In development, allow the React dev server (port 5173)
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",   # Vite dev server
        "http://localhost:3000",   # Create React App (if used)
        "http://127.0.0.1:5173",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Routers ───────────────────────────────────────────────────────────────────
app.include_router(auth.router)
app.include_router(documents.router)
app.include_router(chat.router)
app.include_router(websocket.router)
app.include_router(system.router)


@app.get("/")
async def root():
    return {
        "name": "NeuroLens API",
        "version": "0.1.0",
        "docs": "/docs",
        "health": "/api/system/health",
    }
